"""
This type stub file was generated by pyright.
"""

import torch.nn as nn

"""
Copyright (c) 2019-present NAVER Corp.
MIT License
"""
class double_conv(nn.Module):
    def __init__(self, in_ch, mid_ch, out_ch) -> None:
        ...
    
    def forward(self, x): # -> Any:
        ...
    


class CRAFT(nn.Module):
    def __init__(self, pretrained=..., freeze=...) -> None:
        ...
    
    def forward(self, x): # -> tuple[Any, Any]:
        """ Base network """
        ...
    


