"""
This type stub file was generated by pyright.
"""

def copyStateDict(state_dict): # -> OrderedDict[Any, Any]:
    ...

def test_net(canvas_size, mag_ratio, net, image, text_threshold, link_threshold, low_text, poly, device, estimate_num_chars=...): # -> tuple[list[Any], list[Any]]:
    ...

def get_detector(trained_model, device=..., quantize=..., cudnn_benchmark=...): # -> CRAFT | DataParallel[CRAFT]:
    ...

def get_textbox(detector, image, canvas_size, mag_ratio, text_threshold, link_threshold, low_text, poly, device, optimal_num_chars=..., **kwargs): # -> list[Any]:
    ...

