"""
This type stub file was generated by pyright.
"""

def export_detector(detector_onnx_save_path, in_shape=..., lang_list=..., model_storage_directory=..., user_network_directory=..., download_enabled=..., dynamic=..., device=..., quantize=..., detector=..., recognizer=...): # -> None:
    ...

def parse_args(): # -> Namespace:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
