"""
This type stub file was generated by pyright.
"""

import sys
from .config import *

if sys.version_info[0] == 2:
    ...
else:
    ...
LOGGER = ...
class Reader:
    def __init__(self, lang_list, gpu=..., model_storage_directory=..., user_network_directory=..., detect_network=..., recog_network=..., download_enabled=..., detector=..., recognizer=..., verbose=..., quantize=..., cudnn_benchmark=...) -> None:
        """Create an EasyOCR Reader

        Parameters:
            lang_list (list): Language codes (ISO 639) for languages to be recognized during analysis.

            gpu (bool): Enable GPU support (default)

            model_storage_directory (string): Path to directory for model data. If not specified,
            models will be read from a directory as defined by the environment variable
            EASYOCR_MODULE_PATH (preferred), MODULE_PATH (if defined), or ~/.EasyOCR/.

            user_network_directory (string): Path to directory for custom network architecture.
            If not specified, it is as defined by the environment variable
            EASYOCR_MODULE_PATH (preferred), MODULE_PATH (if defined), or ~/.EasyOCR/.

            download_enabled (bool): Enabled downloading of model data via HTTP (default).
        """
        ...
    
    def getDetectorPath(self, detect_network): # -> str:
        ...
    
    def initDetector(self, detector_path): # -> DBNet | CRAFT | DataParallel[CRAFT]:
        ...
    
    def setDetector(self, detect_network): # -> None:
        ...
    
    def setModelLanguage(self, language, lang_list, list_lang, list_lang_string): # -> None:
        ...
    
    def getChar(self, fileName): # -> str:
        ...
    
    def setLanguageList(self, lang_list, model): # -> None:
        ...
    
    def detect(self, img, min_size=..., text_threshold=..., low_text=..., link_threshold=..., canvas_size=..., mag_ratio=..., slope_ths=..., ycenter_ths=..., height_ths=..., width_ths=..., add_margin=..., reformat=..., optimal_num_chars=..., threshold=..., bbox_min_score=..., bbox_min_size=..., max_candidates=...): # -> tuple[list[Any], list[Any]]:
        ...
    
    def recognize(self, img_cv_grey, horizontal_list=..., free_list=..., decoder=..., beamWidth=..., batch_size=..., workers=..., allowlist=..., blocklist=..., detail=..., rotation_info=..., paragraph=..., contrast_ths=..., adjust_contrast=..., filter_ths=..., y_ths=..., x_ths=..., reformat=..., output_format=...): # -> list[Any] | list[dict[str, Any]] | list[str] | list[list[Any]]:
        ...
    
    def readtext(self, image, decoder=..., beamWidth=..., batch_size=..., workers=..., allowlist=..., blocklist=..., detail=..., rotation_info=..., paragraph=..., min_size=..., contrast_ths=..., adjust_contrast=..., filter_ths=..., text_threshold=..., low_text=..., link_threshold=..., canvas_size=..., mag_ratio=..., slope_ths=..., ycenter_ths=..., height_ths=..., width_ths=..., y_ths=..., x_ths=..., add_margin=..., threshold=..., bbox_min_score=..., bbox_min_size=..., max_candidates=..., output_format=...): # -> list[Any] | list[dict[str, Any]] | list[str] | list[list[Any]]:
        '''
        Parameters:
        image: file path or numpy-array or a byte stream object
        '''
        ...
    
    def readtextlang(self, image, decoder=..., beamWidth=..., batch_size=..., workers=..., allowlist=..., blocklist=..., detail=..., rotation_info=..., paragraph=..., min_size=..., contrast_ths=..., adjust_contrast=..., filter_ths=..., text_threshold=..., low_text=..., link_threshold=..., canvas_size=..., mag_ratio=..., slope_ths=..., ycenter_ths=..., height_ths=..., width_ths=..., y_ths=..., x_ths=..., add_margin=..., threshold=..., bbox_min_score=..., bbox_min_size=..., max_candidates=..., output_format=...): # -> None:
        '''
        Parameters:
        image: file path or numpy-array or a byte stream object
        '''
        ...
    
    def readtext_batched(self, image, n_width=..., n_height=..., decoder=..., beamWidth=..., batch_size=..., workers=..., allowlist=..., blocklist=..., detail=..., rotation_info=..., paragraph=..., min_size=..., contrast_ths=..., adjust_contrast=..., filter_ths=..., text_threshold=..., low_text=..., link_threshold=..., canvas_size=..., mag_ratio=..., slope_ths=..., ycenter_ths=..., height_ths=..., width_ths=..., y_ths=..., x_ths=..., add_margin=..., threshold=..., bbox_min_score=..., bbox_min_size=..., max_candidates=..., output_format=...): # -> list[Any]:
        '''
        Parameters:
        image: file path or numpy-array or a byte stream object
        When sending a list of images, they all must of the same size,
        the following parameters will automatically resize if they are not None
        n_width: int, new width
        n_height: int, new height
        '''
        ...
    


