"""
This type stub file was generated by pyright.
"""

"""  
Copyright (c) 2019-present NAVER Corp.
MIT License
"""
def loadImage(img_file): # -> NDArray[Any]:
    ...

def normalizeMeanVariance(in_img, mean=..., variance=...):
    ...

def denormalizeMeanVariance(in_img, mean=..., variance=...):
    ...

def resize_aspect_ratio(img, square_size, interpolation, mag_ratio=...): # -> tuple[_Array[tuple[int, int, int], floating[_32Bit]], Any, tuple[int, int]]:
    ...

def cvt2HeatmapImg(img):
    ...

