"""
This type stub file was generated by pyright.
"""

import sys

if sys.version_info[0] == 2:
    ...
else:
    ...
def consecutive(data, mode=..., stepsize=...): # -> list[Any]:
    ...

def word_segmentation(mat, separator_idx=..., separator_idx_list=...): # -> list[Any]:
    ...

class BeamEntry:
    "information about one single beam at specific time-step"
    def __init__(self) -> None:
        ...
    


class BeamState:
    "information about the beams at specific time-step"
    def __init__(self) -> None:
        ...
    
    def norm(self): # -> None:
        "length-normalise LM score"
        ...
    
    def sort(self): # -> list[Any]:
        "return beam-labelings, sorted by probability"
        ...
    
    def wordsearch(self, classes, ignore_idx, maxCandidate, dict_list): # -> Literal['']:
        ...
    


def applyLM(parentBeam, childBeam, classes, lm): # -> None:
    "calculate LM score of child beam by taking score from parent beam and bigram probability of last two chars"
    ...

def simplify_label(labeling, blankIdx=...): # -> tuple[Any, ...]:
    ...

def fast_simplify_label(labeling, c, blankIdx=...): # -> tuple[Any, ...]:
    ...

def addBeam(beamState, labeling): # -> None:
    "add beam if it does not yet exist"
    ...

def ctcBeamSearch(mat, classes, ignore_idx, lm, beamWidth=..., dict_list=...): # -> Literal['']:
    ...

class CTCLabelConverter:
    """ Convert between text-label and text-index """
    def __init__(self, character, separator_list=..., dict_pathlist=...) -> None:
        ...
    
    def encode(self, text, batch_max_length=...): # -> tuple[IntTensor, IntTensor]:
        """convert text-label into text-index.
        input:
            text: text labels of each image. [batch_size]

        output:
            text: concatenated text index for CTCLoss.
                    [sum(text_lengths)] = [text_index_0 + text_index_1 + ... + text_index_(n - 1)]
            length: length of each text. [batch_size]
        """
        ...
    
    def decode_greedy(self, text_index, length): # -> list[Any]:
        """ convert text-index into text-label. """
        ...
    
    def decode_beamsearch(self, mat, beamWidth=...): # -> list[Any]:
        ...
    
    def decode_wordbeamsearch(self, mat, beamWidth=...): # -> list[Any]:
        ...
    


def merge_to_free(merge_result, free_list): # -> list[Any]:
    ...

def four_point_transform(image, rect): # -> MatLike:
    ...

def group_text_box(polys, slope_ths=..., ycenter_ths=..., height_ths=..., width_ths=..., add_margin=..., sort_output=...): # -> tuple[list[Any], list[Any]]:
    ...

def calculate_ratio(width, height):
    '''
    Calculate aspect ratio for normal use case (w>h) and vertical text (h>w)
    '''
    ...

def compute_ratio_and_resize(img, width, height, model_height): # -> tuple[Any, Any]:
    '''
    Calculate ratio and resize correctly for both horizontal text
    and vertical case
    '''
    ...

def get_image_list(horizontal_list, free_list, img, model_height=..., sort_output=...): # -> tuple[list[Any], int]:
    ...

def download_and_unzip(url, filename, model_storage_directory, verbose=...): # -> None:
    ...

def calculate_md5(fname): # -> str:
    ...

def diff(input_list):
    ...

def get_paragraph(raw_result, x_ths=..., y_ths=..., mode=...): # -> list[Any]:
    ...

def printProgressBar(prefix=..., suffix=..., decimals=..., length=..., fill=...): # -> Callable[..., None]:
    """
    Call in a loop to create terminal progress bar
    @params:
        prefix      - Optional  : prefix string (Str)
        suffix      - Optional  : suffix string (Str)
        decimals    - Optional  : positive number of decimals in percent complete (Int)
        length      - Optional  : character length of bar (Int)
        fill        - Optional  : bar fill character (Str)
        printEnd    - Optional  : end character (e.g. "\r", "\r\n") (Str)
    """
    ...

def reformat_input(image): # -> tuple[NDArray[Any] | Any | Mat | NumPyArrayNumeric | ndarray[_AnyShape, dtype[Any]], MatLike | Any | ndarray[_AnyShape, dtype[Any]] | None]:
    ...

def reformat_input_batched(image, n_width=..., n_height=...): # -> tuple[NDArray[Any] | Any | Mat | NumPyArrayNumeric | ndarray[_AnyShape, dtype[Any]], NDArray[Any] | Mat | NumPyArrayNumeric | Any | ndarray[_AnyShape, dtype[Any]] | None]:
    """
    reformats an image or list of images or a 4D numpy image array &
    returns a list of corresponding img, img_cv_grey nd.arrays
    image:
        [file path, numpy-array, byte stream object,
        list of file paths, list of numpy-array, 4D numpy array,
        list of byte stream objects]
    """
    ...

def make_rotated_img_list(rotationInfo, img_list):
    ...

def set_result_with_confidence(results): # -> list[Any]:
    """ Select highest confidence augmentation for TTA
    Given a list of lists of results (outer list has one list per augmentation,
    inner lists index the images being recognized), choose the best result 
    according to confidence level.
    Each "result" is of the form (box coords, text, confidence)
    A final_result is returned which contains one result for each image
    """
    ...

