"""
This type stub file was generated by pyright.
"""

from .language_tag import LanguageTag
from .match import Match
from .server import LanguageTool, LanguageToolPublicAPI
from . import utils

"""LanguageTool API for Python."""
