"""
This type stub file was generated by pyright.
"""

import argparse
from typing import Any, Optional, Set, Union

"""LanguageTool command line."""
__version__ = ...
def parse_args() -> argparse.Namespace:
    """
    Parse command line arguments.

    :return: parsed arguments
    :rtype: argparse.Namespace
    """
    ...

class RulesAction(argparse.Action):
    """
    Custom argparse action to update a set of rules in the namespace.
    This action is used to modify the set of rules stored in the argparse
    namespace when the action is triggered. It updates the attribute specified
    by 'self.dest' with the provided values.

    Attributes:
        dest (str): the destination attribute to update
    """
    def __call__(self, parser: argparse.ArgumentParser, namespace: Any, values: Any, option_string: Optional[str] = ...): # -> None:
        """
        This method is called when the action is triggered. It updates the set of rules
        in the namespace with the provided values. The method is invoked automatically
        by argparse when the corresponding command-line argument is encountered.

        :param parser: The ArgumentParser object which contains this action.
        :type parser: argparse.ArgumentParser
        :param namespace: The namespace object that will be returned by parse_args().
        :type namespace: Any
        :param values: The argument values associated with the action.
        :type values: Any
        :param option_string: The option string that was used to invoke this action.
        :type option_string: Optional[str]
        """
        ...
    


def get_rules(rules: str) -> Set[str]:
    """
    Parse a string of rules and return a set of rule IDs.

    :param rules: A string containing rule IDs separated by non-word characters.
    :type rules: str
    :return: A set of rule IDs.
    :rtype: Set[str]
    """
    ...

def get_text(filename: Union[str, int], encoding: Optional[str], ignore: Optional[str]) -> str:
    """
    Read the content of a file and return it as a string, optionally ignoring lines that match a regular expression.

    :param filename: The name of the file to read or file descriptor.
    :type filename: Union[str, int]
    :param encoding: The encoding to use for reading the file.
    :type encoding: Optional[str]
    :param ignore: A regular expression pattern to match lines that should be ignored.
    :type ignore: Optional[str]
    :return: The content of the file as a string.
    :rtype: str
    """
    ...

def main() -> int:
    """
    Main function to parse arguments, process files, and check text using LanguageTool.

    :return: Exit status code
    :rtype: int
    """
    ...

