"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

"""Module for configuring LanguageTool's local server."""
ALLOWED_CONFIG_KEYS = ...
class LanguageToolConfig:
    """
    Configuration class for LanguageTool.

    :param config: Dictionary containing configuration keys and values.
    :type config: Dict[str, Any]

    Attributes:
        config (Dict[str, Any]): Dictionary containing configuration keys and values.
        path (str): Path to the temporary file storing the configuration.
    """
    config: Dict[str, Any]
    path: str
    def __init__(self, config: Dict[str, Any]) -> None:
        """
        Initialize the LanguageToolConfig object.
        """
        ...
    


