"""
This type stub file was generated by pyright.
"""

import zipfile
from typing import Dict, IO, Optional, Tuple

"""LanguageTool download module."""
logger = ...
BASE_URL_SNAPSHOT = ...
FILENAME_SNAPSHOT = ...
BASE_URL_RELEASE = ...
FILENAME_RELEASE = ...
LTP_DOWNLOAD_VERSION = ...
LT_SNAPSHOT_CURRENT_VERSION = ...
JAVA_VERSION_REGEX = ...
JAVA_VERSION_REGEX_UPDATED = ...
def parse_java_version(version_text: str) -> Tuple[int, int]:
    """
    Parse the Java version from a given version text.

    This function attempts to extract the major version numbers from the provided
    Java version string using regular expressions. It supports two different
    version formats defined by JAVA_VERSION_REGEX and JAVA_VERSION_REGEX_UPDATED.

    :param version_text: The Java version string to parse.
    :type version_text: str
    :return: A tuple containing the major version numbers.
    :rtype: Tuple[int, int]
    :raises SystemExit: If the version string cannot be parsed.
    """
    ...

def confirm_java_compatibility(language_tool_version: Optional[str] = ...) -> None:
    """
    Confirms if the installed Java version is compatible with language-tool-python.
    This function checks if Java is installed and verifies that the major version is at least 8 or 17 (depending on the LanguageTool version).
    It raises an error if Java is not installed or if the version is incompatible.

    :param language_tool_version: The version of LanguageTool to check compatibility for.
    :type language_tool_version: Optional[str]
    :raises ModuleNotFoundError: If no Java installation is detected.
    :raises SystemError: If the detected Java version is less than the required version.
    """
    ...

def get_common_prefix(z: zipfile.ZipFile) -> Optional[str]:
    """
    Determine the common prefix of all file names in a zip archive.

    :param z: A ZipFile object representing the zip archive.
    :type z: zipfile.ZipFile
    :return: The common prefix of all file names in the zip archive, or None if there is no common prefix.
    :rtype: Optional[str]
    """
    ...

def http_get(url: str, out_file: IO[bytes], proxies: Optional[Dict[str, str]] = ...) -> None:
    """
    Downloads a file from a given URL and writes it to the specified output file.

    :param url: The URL to download the file from.
    :type url: str
    :param out_file: The file object to write the downloaded content to.
    :type out_file: IO[bytes]
    :param proxies: Optional dictionary of proxies to use for the request.
    :type proxies: Optional[Dict[str, str]]
    :raises PathError: If the file could not be found at the given URL (HTTP 404).
    """
    ...

def unzip_file(temp_file_name: str, directory_to_extract_to: str) -> None:
    """
    Unzips a zip file to a specified directory.

    :param temp_file_name: A temporary file object representing the zip file to be extracted.
    :type temp_file_name: str
    :param directory_to_extract_to: The directory where the contents of the zip file will be extracted.
    :type directory_to_extract_to: str
    """
    ...

def download_zip(url: str, directory: str) -> None:
    """
    Downloads a ZIP file from the given URL and extracts it to the specified directory.

    :param url: The URL of the ZIP file to download.
    :type url: str
    :param directory: The directory where the ZIP file should be extracted.
    :type directory: str
    """
    ...

def download_lt(language_tool_version: Optional[str] = ...) -> None:
    """
    Downloads and extracts the specified version of LanguageTool.
    This function checks for Java compatibility, creates the necessary download
    directory if it does not exist, and downloads the specified version of
    LanguageTool if it is not already present.

    :param language_tool_version: The version of LanguageTool to download. If not
                                  specified, the default version defined by
                                  LTP_DOWNLOAD_VERSION is used.
    :type language_tool_version: Optional[str]
    :raises AssertionError: If the download folder is not a directory.
    :raises ValueError: If the specified version format is invalid.
    """
    ...

