"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable
from functools import total_ordering

"""LanguageTool language tag normalization module."""
@total_ordering
class LanguageTag:
    """
    A class to represent and normalize language tags.

    :param tag: The language tag.
    :type tag: str
    :param languages: An iterable of supported language tags.
    :type languages: Iterable[str]

    Attributes:
        tag (str): The language tag to be normalized.
        languages (Iterable[str]): An iterable of supported language tags.
        normalized_tag (str): The normalized language tag.
        _LANGUAGE_RE (re.Pattern): A regular expression to match language tags. 
    """
    _LANGUAGE_RE = ...
    def __init__(self, tag: str, languages: Iterable[str]) -> None:
        """
        Initialize a LanguageTag instance.
        """
        ...
    
    def __eq__(self, other: Any) -> bool:
        """
        Compare this LanguageTag object with another for equality.

        :param other: The other object to compare with.
        :type other: Any
        :return: True if the normalized tags are equal, False otherwise.
        :rtype: bool
        """
        ...
    
    def __lt__(self, other: Any) -> bool:
        """
        Compare this object with another for less-than ordering.

        :param other: The object to compare with.
        :type other: Any
        :return: True if this object is less than the other, False otherwise.
        :rtype: bool
        """
        ...
    
    def __str__(self) -> str:
        """
        Returns the string representation of the object.

        :return: The normalized tag as a string.
        :rtype: str
        """
        ...
    
    def __repr__(self) -> str:
        """
        Return a string representation of the LanguageTag instance.

        :return: A string in the format '<LanguageTag "language_tag_string">'
        :rtype: str
        """
        ...
    


