"""
This type stub file was generated by pyright.
"""

import atexit
import subprocess
import threading
from typing import Any, List, Optional
from .language_tag import LanguageTag
from .match import Match

"""LanguageTool server management module."""
DEBUG_MODE = ...
RUNNING_SERVER_PROCESSES: List[subprocess.Popen] = ...
class LanguageTool:
    """
    A class to interact with the LanguageTool server for text checking and correction.

    :param language: The language to be used by the LanguageTool server. If None, it will try to detect the system language.
    :type language: Optional[str]
    :param motherTongue: The mother tongue of the user.
    :type motherTongue: Optional[str]
    :param remote_server: URL of a remote LanguageTool server. If provided, the local server will not be started.
    :type remote_server: Optional[str]
    :param newSpellings: Custom spellings to be added to the LanguageTool server.
    :type newSpellings: Optional[List[str]]
    :param new_spellings_persist: Whether the new spellings should persist across sessions.
    :type new_spellings_persist: Optional[bool]
    :param host: The host address for the LanguageTool server. Defaults to 'localhost'.
    :type host: Optional[str]
    :param config: Path to a configuration file for the LanguageTool server.
    :type config: Optional[str]
    :param language_tool_download_version: The version of LanguageTool to download if needed.
    :type language_tool_download_version: Optional[str]
    
    Attributes:
        _MIN_PORT (int): The minimum port number to use for the server.
        _MAX_PORT (int): The maximum port number to use for the server.
        _TIMEOUT (int): The timeout for server requests.
        _remote (bool): A flag to indicate if the server is remote.
        _port (int): The port number to use for the server.
        _server (subprocess.Popen): The server process.
        _consumer_thread (threading.Thread): The thread to consume server output.
        _PORT_RE (re.Pattern): A compiled regular expression pattern to match the server port.
        language_tool_download_version (str): The version of LanguageTool to download.
        _new_spellings (List[str]): A list of new spellings to register.
        _new_spellings_persist (bool): A flag to indicate if new spellings should persist.
        _host (str): The host to use for the server.
        config (LanguageToolConfig): The configuration to use for the server.
        _url (str): The URL of the server if remote.
        _stop_consume_event (threading.Event): An event to signal the consumer thread to stop.
        motherTongue (str): The user's mother tongue (used in requests to the server).
        disabled_rules (Set[str]): A set of disabled rules (used in requests to the server).
        enabled_rules (Set[str]): A set of enabled rules (used in requests to the server).
        disabled_categories (Set[str]): A set of disabled categories (used in requests to the server).
        enabled_categories (Set[str]): A set of enabled categories (used in requests to the server).
        enabled_rules_only (bool): A flag to indicate if only enabled rules should be used (used in requests to the server).
        preferred_variants (Set[str]): A set of preferred variants (used in requests to the server).
        picky (bool): A flag to indicate if the tool should be picky (used in requests to the server).
        language (str): The language to use (used in requests to the server and in other methods).
        _spell_checking_categories (Set[str]): A set of spell-checking categories.
    """
    _MIN_PORT = ...
    _MAX_PORT = ...
    _TIMEOUT = ...
    _remote = ...
    _port = ...
    _server: subprocess.Popen = ...
    _consumer_thread: threading.Thread = ...
    _PORT_RE = ...
    def __init__(self, language=..., motherTongue=..., remote_server=..., newSpellings=..., new_spellings_persist=..., host=..., config=..., language_tool_download_version: str = ...) -> None:
        """
        Initialize the LanguageTool server.
        """
        ...
    
    def __enter__(self) -> LanguageTool:
        """
        Enter the runtime context related to this object.

        This method is called when execution flow enters the context of the
        `with` statement using this object. It returns the object itself.

        :return: The object itself.
        :rtype: LanguageTool
        """
        ...
    
    def __exit__(self, exc_type: Optional[type], exc_val: Optional[BaseException], exc_tb: Optional[Any]) -> None:
        """
        Exit the runtime context related to this object.
        This method is called when the runtime context is exited. It can be used to 
        clean up any resources that were allocated during the context. The parameters 
        describe the exception that caused the context to be exited. If the context 
        was exited without an exception, all three arguments will be None.

        :param exc_type: The exception type of the exception that caused the context 
                         to be exited, or None if no exception occurred.
        :type exc_type: Optional[type]
        :param exc_val: The exception instance that caused the context to be exited, 
                        or None if no exception occurred.
        :type exc_val: Optional[BaseException]
        :param exc_tb: The traceback object associated with the exception, or None 
                       if no exception occurred.
        :type exc_tb: Optional[Any]
        """
        ...
    
    def __del__(self) -> None:
        """
        Destructor method that ensures the server is properly closed.
        This method is called when the instance is about to be destroyed. It 
        ensures that the `close` method is called to release any resources 
        or perform any necessary cleanup.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Return a string representation of the server instance.

        :return: A string that includes the class name, language, and mother tongue.
        :rtype: str
        """
        ...
    
    def close(self) -> None:
        """
        Closes the server and performs necessary cleanup operations.

        This method performs the following actions:
        1. Checks if the server is alive and terminates it if necessary.
        2. If new spellings are not set to persist and there are new spellings,
           it unregisters the spellings and clears the list of new spellings.
        """
        ...
    
    @property
    def language(self) -> LanguageTag:
        """
        Returns the language tag associated with the server.

        :return: The language tag.
        :rtype: LanguageTag
        """
        ...
    
    @language.setter
    def language(self, language: str) -> None:
        """
        Sets the language for the language tool.

        :param language: The language code to set.
        :type language: str
        """
        ...
    
    @property
    def motherTongue(self) -> Optional[LanguageTag]:
        """
        Retrieve the mother tongue language tag.

        :return: The mother tongue language tag if set, otherwise None.
        :rtype: Optional[LanguageTag]
        """
        ...
    
    @motherTongue.setter
    def motherTongue(self, motherTongue: Optional[str]) -> None:
        """
        Sets the mother tongue for the language tool.

        :param motherTongue: The mother tongue language tag as a string. If None, the mother tongue is set to None.
        :type motherTongue: Optional[str]
        """
        ...
    
    def check(self, text: str) -> List[Match]:
        """
        Checks the given text for language issues using the LanguageTool server.

        :param text: The text to be checked for language issues.
        :type text: str
        :return: A list of Match objects representing the issues found in the text.
        :rtype: List[Match]
        """
        ...
    
    def correct(self, text: str) -> str:
        """
        Corrects the given text by applying language tool suggestions. Applies only the first suggestion for each issue.

        :param text: The text to be corrected.
        :type text: str
        :return: The corrected text.
        :rtype: str
        """
        ...
    
    def enable_spellchecking(self) -> None:
        """
        Enable spellchecking by removing spell checking categories from the disabled categories set.
        This method updates the `disabled_categories` attribute by removing any categories that are 
        related to spell checking, which are defined in the `_spell_checking_categories` attribute.
        """
        ...
    
    def disable_spellchecking(self) -> None:
        """
        Disable spellchecking by updating the disabled categories with spell checking categories.
        """
        ...
    


class LanguageToolPublicAPI(LanguageTool):
    """
    A class to interact with the public LanguageTool API.
    This class extends the `LanguageTool` class and initializes it with the
    remote server set to the public LanguageTool API endpoint.

    :param args: Positional arguments passed to the parent class initializer.
    :type args: Any
    :param kwargs: Keyword arguments passed to the parent class initializer.
    :type kwargs: Any
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """
        Initialize the server with the given arguments.
        """
        ...
    


@atexit.register
def terminate_server() -> None:
    """
    Terminates all running server processes.
    This function iterates over the list of running server processes and 
    forcefully kills each process by its PID.
    """
    ...

