"""
This type stub file was generated by pyright.
"""

import os
import psutil
from typing import List, Optional, Tuple
from enum import Enum
from .config_file import LanguageToolConfig
from .match import Match

"""Utility functions for the LanguageTool library."""
JAR_NAMES = ...
FAILSAFE_LANGUAGE = ...
LTP_PATH_ENV_VAR = ...
LTP_JAR_DIR_PATH_ENV_VAR = ...
if os.name == 'nt':
    startupinfo = ...
else:
    ...
class LanguageToolError(Exception):
    """
    Exception raised for errors in the LanguageTool library.
    This is a generic exception that can be used to indicate various types of
    errors encountered while using the LanguageTool library.
    """
    ...


class ServerError(LanguageToolError):
    """
    Exception raised for errors that occur when interacting with the LanguageTool server.
    This exception is a subclass of `LanguageToolError` and is used to indicate
    issues such as server startup failures.
    """
    ...


class JavaError(LanguageToolError):
    """
    Exception raised for errors related to the Java backend of LanguageTool.
    This exception is a subclass of `LanguageToolError` and is used to indicate
    issues that occur when interacting with Java, such as Java not being found.
    """
    ...


class PathError(LanguageToolError):
    """
    Exception raised for errors in the file path used in LanguageTool.
    This error is raised when there is an issue with the file path provided
    to LanguageTool, such as the LanguageTool JAR file not being found,
    or a download path not being a valid available file path.
    """
    ...


class RateLimitError(LanguageToolError):
    """
    Exception raised for errors related to rate limiting in the LanguageTool server.
    This exception is a subclass of `LanguageToolError` and is used to indicate
    issues such as exceeding the allowed number of requests to the public API without a key.
    """
    ...


def parse_url(url_str: str) -> str:
    """
    Parse the given URL string and ensure it has a scheme.
    If the input URL string does not contain 'http', 'http://' is prepended to it.
    The function then parses the URL and returns its canonical form.

    :param url_str: The URL string to be parsed.
    :type url_str: str
    :return: The parsed URL in its canonical form.
    :rtype: str
    """
    ...

class TextStatus(Enum):
    CORRECT = ...
    FAULTY = ...
    GARBAGE = ...


def classify_matches(matches: List[Match]) -> TextStatus:
    """
    Classify the matches (result of a check on a text) into one of three categories:
    CORRECT, FAULTY, or GARBAGE.
    This function checks the status of the matches and returns a corresponding
    `TextStatus` value.

    :param matches: A list of Match objects to be classified.
    :type matches: List[Match]
    :return: The classification of the matches as a `TextStatus` value.
    :rtype: TextStatus
    """
    ...

def correct(text: str, matches: List[Match]) -> str:
    """
    Corrects the given text based on the provided matches.
    Only the first replacement for each match is applied to the text.

    :param text: The original text to be corrected.
    :type text: str
    :param matches: A list of Match objects that contain the positions and replacements for errors in the text.
    :type matches: List[Match]
    :return: The corrected text.
    :rtype: str
    """
    ...

def get_language_tool_download_path() -> str:
    """
    Get the download path for LanguageTool.
    This function retrieves the download path for LanguageTool from the environment variable
    specified by `LTP_PATH_ENV_VAR`. If the environment variable is not set, it defaults to
    a path in the user's home directory under `.cache/language_tool_python`.

    :return: The download path for LanguageTool.
    :rtype: str
    """
    ...

def find_existing_language_tool_downloads(download_folder: str) -> List[str]:
    """
    Find existing LanguageTool downloads in the specified folder.
    This function searches for directories in the given download folder
    that match the pattern 'LanguageTool*' and returns a list of their paths.

    :param download_folder: The folder where LanguageTool downloads are stored.
    :type download_folder: str
    :return: A list of paths to the existing LanguageTool download directories.
    :rtype: List[str]
    """
    ...

def get_language_tool_directory() -> str:
    """
    Get the directory path of the LanguageTool installation.
    This function checks the download folder for LanguageTool installations,
    verifies that the folder exists and is a directory, and returns the path
    to the latest version of LanguageTool found in the directory.

    :raises NotADirectoryError: If the download folder path is not a valid directory.
    :raises FileNotFoundError: If no LanguageTool installation is found in the download folder.
    :return: The path to the latest version of LanguageTool found in the directory.
    :rtype: str
    """
    ...

def get_server_cmd(port: Optional[int] = ..., config: Optional[LanguageToolConfig] = ...) -> List[str]:
    """
    Generate the command to start the LanguageTool HTTP server.

    :param port: Optional; The port number on which the server should run. If not provided, the default port will be used.
    :type port: Optional[int]
    :param config: Optional; The configuration for the LanguageTool server. If not provided, default configuration will be used.
    :type config: Optional[LanguageToolConfig]
    :return: A list of command line arguments to start the LanguageTool HTTP server.
    :rtype: List[str]
    """
    ...

def get_jar_info() -> Tuple[str, str]:
    """
    Retrieve the path to the Java executable and the LanguageTool JAR file.
    This function searches for the Java executable in the system's PATH and 
    locates the LanguageTool JAR file either in a directory specified by an 
    environment variable or in a default download directory.

    :raises JavaError: If the Java executable cannot be found.
    :raises PathError: If the LanguageTool JAR file cannot be found in the specified directory.
    :return: A tuple containing the path to the Java executable and the path to the LanguageTool JAR file.
    :rtype: Tuple[str, str]
    """
    ...

def get_locale_language() -> str:
    """
    Get the current locale language.
    This function retrieves the current locale language setting of the system.
    It first attempts to get the locale using `locale.getlocale()`. If that fails,
    it falls back to using `locale.getdefaultlocale()`.

    :return: The language code of the current locale.
    :rtype: str
    """
    ...

def kill_process_force(*, pid: Optional[int] = ..., proc: Optional[psutil.Process] = ...) -> None:
    """
    Forcefully kills a process and all its child processes.
    This function attempts to kill a process specified either by its PID or by a psutil.Process object.
    If the process has any child processes, they will be killed first.

    :param pid: The process ID of the process to be killed. Either `pid` or `proc` must be provided.
    :type pid: Optional[int]
    :param proc: A psutil.Process object representing the process to be killed. Either `pid` or `proc` must be provided.
    :type proc: Optional[psutil.Process]
    :raises AssertionError: If neither `pid` nor `proc` is provided.
    """
    ...

