"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn

def init_weights(modules): # -> None:
    ...

class vgg16_bn(torch.nn.Module):
    def __init__(self, pretrained=..., freeze=...) -> None:
        ...
    
    def forward(self, X): # -> VggOutputs:
        ...
    


class BidirectionalLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, output_size) -> None:
        ...
    
    def forward(self, input): # -> Any:
        """
        input : visual feature [batch_size x T x input_size]
        output : contextual feature [batch_size x T x output_size]
        """
        ...
    


class VGG_FeatureExtractor(nn.Module):
    def __init__(self, input_channel, output_channel=...) -> None:
        ...
    
    def forward(self, input): # -> Any:
        ...
    


class ResNet_FeatureExtractor(nn.Module):
    """ FeatureExtractor of FAN (http://openaccess.thecvf.com/content_ICCV_2017/papers/Cheng_Focusing_Attention_Towards_ICCV_2017_paper.pdf) """
    def __init__(self, input_channel, output_channel=...) -> None:
        ...
    
    def forward(self, input): # -> Any:
        ...
    


class BasicBlock(nn.Module):
    expansion = ...
    def __init__(self, inplanes, planes, stride=..., downsample=...) -> None:
        ...
    
    def forward(self, x): # -> Any:
        ...
    


class ResNet(nn.Module):
    def __init__(self, input_channel, output_channel, block, layers) -> None:
        ...
    
    def forward(self, x): # -> Any:
        ...
    


